const execSync = require("child_process").execSync;
const validateName = require("validate-npm-package-name");

function getAuthor() {
  const defaultAuthor = "create-mp-generator";

  try {
    const userName =
      execSync("git config user.name").toString().trim() || defaultAuthor;
    const userEmail =
      execSync("git config user.email").toString().trim() || null;

    return userEmail ? `${userName}<${userEmail}>` : userName;
  } catch (error) {
    return defaultAuthor;
  }
}

module.exports = {
  getPrompts(name) {
    return [
      {
        type: "string",
        name: "name",
        message: "请输入项目名称",
        default: name,
        validate: (input) => {
          const {
            validForNewPackages,
            errors = [],
            warnings = [],
          } = validateName(input);
          if (!validForNewPackages) {
            const messages = errors.concat(warnings);
            return "Sorry, " + messages.join(" and ") + ".";
          }

          return true;
        },
      },
      {
        type: "string",
        name: "author",
        message: "请输入项目作者",
        default: getAuthor(),
      },
      {
        type: "string",
        name: "description",
        message: "请输入项目描述",
        default: "miniprogram app generated by create-mp-generator",
      },
    ];
  },
};
